<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

<head>
<link rel="stylesheet" href="inscri.css">
</head>
<div class="card">
    <div class=" ">
        <div class="">
            <div class="">
           
                <div class="">
                    <h1 class="">Creation du Compte</h1>
                    <form action="Inscription.php" method="post" class="">

                        <div class="mb-2">
                            <input 
                                type="text" 
                                name="nom" 
                                placeholder="Nom"
                                class="form-control <?= isset($errors['nom']) ? 'is-invalid' : '' ?>"
                                value="<?= htmlspecialchars($nom ?? '') ?>"
                            >
                            <small class="text-danger"><?= $errors['nom'] ?? '' ?></small>
                        </div>
                        <div class="mb-2">
                            <input 
                                type="text" 
                                placeholder="Prenom" 
                                name="prenom"
                                class="form-control <?= isset($errors['prenom']) ? 'is-invalid' : '' ?>"
                                value="<?= htmlspecialchars($prenom ?? '') ?>"
                            >
                            <small class="text-danger"><?= $errors['prenom'] ?? '' ?></small>
                        </div>

                        <div class="mb-2">
                            <input 
                                type="email" 
                                placeholder="Email" 
                                name="email"
                                class="form-control <?= isset($errors['email']) ? 'is-invalid' : '' ?>"
                                value="<?= htmlspecialchars($email ?? '') ?>"
                            >
                            <small class="text-danger"><?= $errors['email'] ?? '' ?></small>
                        </div>

                        <div class="input-group">
                            <input 
                                type="password" 
                                name="password"
                                class="form-control pwd <?= isset($errors['password']) ? 'is-invalid' : '' ?>"
                                placeholder="" 
                                value="<?= htmlspecialchars($password ?? '') ?>">
                          
                        </div>
                        <small class=""><?= $errors['password'] ?? '' ?></small>


                        <div class="">
                            <button name="submit" type="submit" class=" signup">S'inscrire</button>
                        </div>
                       <a href="login.php">Connexion</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</script>